version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL} # Path to SQLite DB inside the container
      INVITE_CODE: ${INVITE_CODE} # Pass the INVITE_CODE from the .env file or shell
      NEXTAUTH_URL: ${NEXTAUTH_URL} # URL of your app
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET} 
    #volumes:
    #  - ./prisma:/app/prisma # Persists the SQLite database and migrations
    # The CMD ["npm", "start"] from your Dockerfile will be used to run the application.
