// Bootstrap ambient types for `tsc --noEmit` on fresh checkouts.
//
// `next-env.d.ts` is generated by `next dev` / `next build` (and gitignored), so a
// clean checkout — a new worktree, or CI before the build step — does not have it.
// Without these references, typechecking fails on static asset imports such as
// `import defaultAvatar from '@/../public/default-avatar.jpg'` in
// src/app/components/FamilyNode.tsx. Mirrors the references written into
// next-env.d.ts; the duplicate reference is harmless when both files exist.
/// <reference types="next" />
/// <reference types="next/image-types/global" />
