'use client';

import React, { useState, useEffect, useCallback, ChangeEvent, FormEvent } from 'react';
import { authClient } from '@/lib/client';
import { useRouter } from 'next/navigation';
import FamilyTreeGraph from './components/FamilyTreeGraph';
import type { FamilyMember as FamilyMemberType } from '@/db/schema';
import Image from 'next/image';

// Define a type for Family (matching /api/families response)
interface Family {
  id: number; // Prisma Int maps to number
  name: string;
}

// Define a type for User (matching /api/families/[familyId]/users response)
interface FamilyUser {
  id: number;
  email: string;
}

// Define a type for the form data state
interface PageFormData {
  id?: string;
  fullName?: string;
  gender?: string;
  birthDate?: string; // Dates are strings for form inputs
  deathDate?: string; // Dates are strings for form inputs
  birthPlace?: string | null;
  pictureUrl?: string | null; // This will store the data URL for preview
  parentId1?: string | null;
  parentId2?: string | null;
  removePicture?: boolean; // Custom flag for form logic
}

// Helper function to convert Uint8Array to base64 string
function uint8ArrayToBase64(buffer: Uint8Array): string {
  let binary = '';
  const len = buffer.byteLength;
  for (let i = 0; i < len; i++) {
    binary += String.fromCharCode(buffer[i]);
  }
  return btoa(binary);
}

// Helper function to ensure picture is a data URL
function ensureDataUrl(picture: Uint8Array | string | null, mimeType: string = 'image/jpeg'): string | null {
  if (!picture) return null;
  if (typeof picture === 'string') {
    // Check if it's already a data URL (common for previews generated by FileReader or already processed)
    if (picture.startsWith('data:image')) {
      return picture;
    }
    // Assuming it might be a base64 string without the prefix
    return `data:${mimeType};base64,${picture}`;
  }
  // If it's Uint8Array, convert to base64 then to data URL
  const base64String = uint8ArrayToBase64(picture);
  return `data:${mimeType};base64,${base64String}`;
}

export default function HomePage() {
  const { data: session, isPending: status } = authClient.useSession();
  const router = useRouter();
  const [familyMembers, setFamilyMembers] = useState<FamilyMemberType[]>([]);
  const [selectedMember, setSelectedMember] = useState<FamilyMemberType | null>(null);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [modalMode, setModalMode] = useState<'add' | 'edit'>('add');
  const [formData, setFormData] = useState<PageFormData>({});
  const [picturePreview, setPicturePreview] = useState<string | null>(null);
  const [pictureFile, setPictureFile] = useState<File | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const [userFamilies, setUserFamilies] = useState<Family[]>([]);
  const [selectedFamilyId, setSelectedFamilyId] = useState<number | null>(null);

  // New state for "Add User to Family" modal
  const [isAddUserModalOpen, setIsAddUserModalOpen] = useState(false);
  const [addUserEmail, setAddUserEmail] = useState('');
  const [addUserFeedback, setAddUserFeedback] = useState<{ type: 'success' | 'error', message: string } | null>(null);
  const [isAddingUser, setIsAddingUser] = useState(false);

  // New state for "Remove User from Family" modal
  const [isRemoveUserModalOpen, setIsRemoveUserModalOpen] = useState(false);
  const [usersInFamilyForRemoval, setUsersInFamilyForRemoval] = useState<FamilyUser[]>([]);
  const [selectedUserToRemoveId, setSelectedUserToRemoveId] = useState<string | null>(null);
  const [removeUserFeedback, setRemoveUserFeedback] = useState<{ type: 'success' | 'error', message: string } | null>(null);
  const [isRemovingUser, setIsRemovingUser] = useState(false);
  const [isLoadingUsersForRemoval, setIsLoadingUsersForRemoval] = useState(false);

  const fetchFamilyMembers = useCallback(async (familyId: number | null) => {
    if (!familyId) {
      setFamilyMembers([]);
      return;
    }
    setIsLoading(true);
    setError(null);
    try {
      const response = await fetch(`/api/family-members?familyId=${familyId}`);
      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.message || 'Failed to fetch family members');
      }
      const data: FamilyMemberType[] = await response.json();
      setFamilyMembers(data);
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'An unknown error occurred while fetching members');
      setFamilyMembers([]);
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    if (status) return;
    if (!session) {
      router.push('/login');
      return;
    }

    const manageUserAndFamilies = async () => {
      setIsLoading(true);
      setError(null);
      try {
        const familiesResponse = await fetch('/api/families');
        if (!familiesResponse.ok) {
          if (familiesResponse.status === 401) {
            router.push('/login');
            return;
          }
          const errorData = await familiesResponse.json();
          throw new Error(errorData.message || 'Failed to fetch user families');
        }
        const familiesData: Family[] = await familiesResponse.json();

        if (familiesData.length === 0) {
          router.push('/create-family');
        } else {
          setUserFamilies(familiesData);
          setSelectedFamilyId(familiesData[0].id);
        }
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Error initializing page');
        setIsLoading(false);
      }
    };

    manageUserAndFamilies();
  }, [session, status, router]);

  useEffect(() => {
    if (selectedFamilyId) {
      fetchFamilyMembers(selectedFamilyId);
    } else if (session && userFamilies.length > 0) {
      setSelectedFamilyId(userFamilies[0].id);
    }
  }, [selectedFamilyId, userFamilies, session, fetchFamilyMembers]);

  const handleNodeClick = (member: FamilyMemberType) => {
    setSelectedMember(member);

    const currentPictureDataUrl = member.picture ? ensureDataUrl(member.picture as Uint8Array) : null;
    const memberDataForForm: PageFormData = {
      id: member.id.toString(),
      fullName: member.fullName,
      gender: member.gender,
      birthDate: member.birthDate ? new Date(member.birthDate).toISOString().split('T')[0] : '',
      deathDate: member.deathDate ? new Date(member.deathDate).toISOString().split('T')[0] : '',
      birthPlace: member.birthPlace,
      pictureUrl: currentPictureDataUrl,
      parentId1: member.parentId1?.toString() || null,
      parentId2: member.parentId2?.toString() || null,
    };
    setFormData(memberDataForForm);
    setPicturePreview(currentPictureDataUrl || null);
    setPictureFile(null);
    setModalMode('edit');
    setIsModalOpen(true);
  };

  const handleAddMemberClick = () => {
    setSelectedMember(null);
    setFormData({
      fullName: '',
      gender: 'Male',
      birthDate: '',
      deathDate: '',
      birthPlace: '',
      parentId1: '',
      parentId2: '',
      pictureUrl: null,
      removePicture: false,
    });
    setPicturePreview(null);
    setPictureFile(null);
    setModalMode('add');
    setIsModalOpen(true);
  };

  const handleCloseModal = () => {
    setIsModalOpen(false);
    setSelectedMember(null);
    setFormData({});
    setPicturePreview(null);
    setPictureFile(null);
    setError(null);
  };

  const handleInputChange = (e: ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handlePictureChange = (e: ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      setPictureFile(file);
      const reader = new FileReader();
      reader.onloadend = () => {
        setPicturePreview(reader.result as string);
      };
      reader.readAsDataURL(file);
    } else {
      if (modalMode === 'edit' && selectedMember) {
        const existingPictureDataUrl = selectedMember.picture ? ensureDataUrl(selectedMember.picture as Uint8Array) : null;
        setPicturePreview(existingPictureDataUrl || '/default-avatar.jpg');
      } else {
        setPicturePreview('/default-avatar.jpg');
      }
      setPictureFile(null);
    }
  };

  const handleRemovePicture = () => {
    setPicturePreview('/default-avatar.jpg');
    setPictureFile(null);
    if (modalMode === 'edit') {
      setFormData(prev => ({ ...prev, pictureUrl: null, removePicture: true }));
    }
  };

  const handleFormSubmit = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setError(null);

    const memberFormData = new FormData();

    if (!selectedFamilyId && modalMode === 'add') {
      setError('No family selected. Cannot add member.');
      setIsLoading(false);
      return;
    }
    if (modalMode === 'add' && selectedFamilyId) {
      memberFormData.append('familyId', selectedFamilyId.toString());
    }

    Object.entries(formData).forEach(([key, value]) => {
      if (key === 'removePicture') return;

      if (value !== null && value !== undefined) {
        if (typeof value === 'string') {
          memberFormData.append(key, value);
        }
      }
    });

    if (pictureFile) {
      memberFormData.append('picture', pictureFile);
    } else if (formData.removePicture && modalMode === 'edit') {
      memberFormData.append('removePicture', 'true');
    }

    const url = modalMode === 'edit' && selectedMember ? `/api/family-members/${selectedMember.id}` : '/api/family-members';
    const method = modalMode === 'edit' ? 'PATCH' : 'POST';
    setIsLoading(true);

    try {
      const response = await fetch(url, {
        method: method,
        body: memberFormData,
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.message || `Failed to ${modalMode === 'edit' ? 'update' : 'add'} member`);
      }

      handleCloseModal();
      if (selectedFamilyId) {
        fetchFamilyMembers(selectedFamilyId);
      }
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'An unknown error occurred');
    } finally {
      setIsLoading(false);
    }
  };

  const handleDeleteMember = async (memberId: string | undefined) => {
    if (!memberId || !window.confirm('Are you sure you want to delete this family member?')) {
      return;
    }

    setError(null);
    setIsLoading(true);

    try {
      const response = await fetch(`/api/family-members/${memberId}`, {
        method: 'DELETE',
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.message || 'Failed to delete member');
      }

      handleCloseModal();
      if (selectedFamilyId) {
        fetchFamilyMembers(selectedFamilyId);
      }
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'An unknown error occurred');
    } finally {
      setIsLoading(false);
    }
  };

  // New handlers for "Add User to Family" modal
  const closeAddUserModal = () => {
    setIsAddUserModalOpen(false);
  };

  const handleAddUserSubmit = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (!selectedFamilyId) {
      setAddUserFeedback({ type: 'error', message: 'No family selected. Cannot add user.' });
      return;
    }
    if (!addUserEmail.trim()) {
      setAddUserFeedback({ type: 'error', message: 'Please enter a valid email address.' });
      return;
    }

    setIsAddingUser(true);
    setAddUserFeedback(null);

    try {
      const response = await fetch(`/api/families/${selectedFamilyId}/members`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ email: addUserEmail }),
      });

      const result = await response.json();

      if (!response.ok) {
        throw new Error(result.message || `Error ${response.status}: Failed to add user to family.`);
      }

      setAddUserFeedback({ type: 'success', message: result.message || 'User successfully added to the family!' });
      setAddUserEmail(''); // Clear input on success
    } catch (error: any) {
      setAddUserFeedback({ type: 'error', message: error.message || 'An unexpected error occurred. Please try again.' });
    } finally {
      setIsAddingUser(false);
    }
  };

  // New handlers for "Remove User from Family" modal
  const fetchUsersInFamily = async (familyId: number) => {
    setIsLoadingUsersForRemoval(true);
    setRemoveUserFeedback(null);
    try {
      const response = await fetch(`/api/families/${familyId}/users`);
      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.message || 'Failed to fetch users in family');
      }
      const data: FamilyUser[] = await response.json();
      setUsersInFamilyForRemoval(data);
      if (data.length > 0) {
        setSelectedUserToRemoveId(data[0].id.toString()); // Pre-select first user
      } else {
        setSelectedUserToRemoveId(null); // No users to select
      }
    } catch (err: any) {
      setRemoveUserFeedback({ type: 'error', message: err.message || 'Could not load users for removal.' });
      setUsersInFamilyForRemoval([]);
    } finally {
      setIsLoadingUsersForRemoval(false);
    }
  };

  const closeRemoveUserModal = () => {
    setIsRemoveUserModalOpen(false);
    setUsersInFamilyForRemoval([]);
    setSelectedUserToRemoveId(null);
    setRemoveUserFeedback(null);
  };

  const handleRemoveUserSubmit = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (!selectedFamilyId || !selectedUserToRemoveId) {
      setRemoveUserFeedback({ type: 'error', message: 'No family or user selected.' });
      return;
    }

    // Confirmation dialog
    if (!window.confirm(`Are you sure you want to remove this user from the family?`)) {
      return;
    }

    setIsRemovingUser(true);
    setRemoveUserFeedback(null);

    try {
      const response = await fetch(`/api/families/${selectedFamilyId}/members/${selectedUserToRemoveId}`, {
        method: 'DELETE',
      });

      const result = await response.json();

      if (!response.ok) {
        throw new Error(result.message || `Error ${response.status}: Failed to remove user.`);
      }

      setRemoveUserFeedback({ type: 'success', message: result.message || 'User successfully removed from the family!' });
      setSelectedUserToRemoveId(null); // Reset selection
      if (selectedFamilyId) {
        fetchUsersInFamily(selectedFamilyId);
      }
    } catch (error: any) {
      setRemoveUserFeedback({ type: 'error', message: error.message || 'An unexpected error occurred. Please try again.' });
    } finally {
      setIsRemovingUser(false);
    }
  };

  if (status || (isLoading && familyMembers.length === 0 && !error && !selectedFamilyId)) {
    return <div className="flex justify-center items-center h-screen">Loading page data...</div>;
  }

  if (!session) {
    return null;
  }

  const renderFamilyTree = () => {
    if (isLoading && familyMembers.length === 0 && selectedFamilyId) {
      return <div className="flex justify-center items-center"><p>Loading family members...</p></div>;
    }
    if (!selectedFamilyId && userFamilies.length > 0 && !isLoading) {
      return <div className="flex justify-center items-center"><p>Selecting family...</p></div>;
    }
    if (familyMembers.length === 0 && !isLoading) {
      return (
        <div className="text-center p-8">
          <p className="text-xl text-gray-700 mb-4">
            This family doesn&apos;t have any members yet.
          </p>
          {selectedFamilyId && (
            <button
              onClick={handleAddMemberClick}
              className="bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
            >
              Add First Family Member
            </button>
          )}
        </div>
      );
    }
    return (
      <FamilyTreeGraph
        familyMembers={familyMembers}
        onNodeClick={handleNodeClick}
        selectedMemberId={selectedMember?.id?.toString() || null}
      />
    );
  };

  return (
    <div className="container mx-auto p-4">
      <header className="flex flex-col sm:flex-row justify-between items-center mb-6 space-y-4 sm:space-y-0">
        <div className="w-full sm:w-auto">
          {userFamilies.length > 0 && selectedFamilyId && (
            <>
              {userFamilies.length > 1 ? (
                <select
                  value={selectedFamilyId}
                  onChange={(e) => setSelectedFamilyId(Number(e.target.value))}
                  className="w-full p-2 border rounded bg-white text-gray-700 shadow-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
                >
                  {userFamilies.map(family => (
                    <option key={family.id} value={family.id}>
                      {family.name || `Family ${family.id}`}
                    </option>
                  ))}
                </select>
              ) : (
                <h1 className="text-xl md:text-2xl font-bold text-gray-800 text-center sm:text-left">
                  {userFamilies.find(f => f.id === selectedFamilyId)?.name || `Family ${selectedFamilyId}`}
                </h1>
              )}
            </>
          )}
        </div>
        <div className="flex flex-col sm:flex-row space-y-2 sm:space-y-0 sm:space-x-2 w-full sm:w-auto">
          {selectedFamilyId && (
            <>
              <button
                onClick={() => authClient.signOut()}
              className="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded shadow hover:shadow-md transition duration-150 ease-in-out w-full sm:w-auto"
            >
              Sign Out
            </button>
            </>
          )}
        </div>
      </header>

      {error && <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-4" role="alert">{error}</div>}

      <div className="bg-gray-50 p-4 rounded-lg shadow min-h-[400px] flex justify-center items-center">
        {renderFamilyTree()}
      </div>

      {/* Existing modal for adding/editing family members */}
      {isModalOpen && (
        <div className="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full flex justify-center items-center z-50">
          <div className="relative bg-white p-8 rounded-lg shadow-xl w-full max-w-lg mx-4">
            <button
              onClick={handleCloseModal}
              className="absolute top-2 right-2 text-gray-500 hover:text-gray-700 text-2xl font-bold"
              aria-label="Close modal"
            >
              &times;
            </button>
            <h2 className="text-xl font-semibold mb-6">{modalMode === 'edit' ? 'Edit' : 'Add'} Family Member</h2>
            {error && <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-4" role="alert">{error}</div>}
            <form onSubmit={handleFormSubmit} className="space-y-4">
              <div className="flex flex-col items-center mb-4">
                <div className="w-24 h-24 rounded-full overflow-hidden border border-gray-300 relative mb-2">
                  <Image
                    src={picturePreview || '/default-avatar.jpg'}
                    alt="Profile picture preview"
                    fill
                    onError={(e) => {
                      (e.target as HTMLImageElement).src = '/default-avatar.jpg';
                      (e.target as HTMLImageElement).srcset = '';
                    }}
                  />
                </div>
                <input
                  type="file"
                  accept="image/*"
                  onChange={handlePictureChange}
                  className="text-sm text-grey-500
                    file:mr-4 file:py-2 file:px-4
                    file:rounded-full file:border-0
                    file:text-sm file:font-semibold
                    file:bg-blue-50 file:text-blue-700
                    hover:file:bg-blue-100"
                />
                {picturePreview && picturePreview !== '/default-avatar.jpg' && (
                  <button
                    type="button"
                    onClick={handleRemovePicture}
                    className="mt-2 text-xs text-red-600 hover:text-red-800"
                  >
                    Remove Picture
                  </button>
                )}
              </div>

              <div>
                <label htmlFor="fullName" className="block text-sm font-medium text-gray-700">Full Name *</label>
                <input
                  type="text"
                  id="fullName"
                  name="fullName"
                  value={formData.fullName || ''}
                  onChange={handleInputChange}
                  required
                  className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                />
              </div>

              <div>
                <label htmlFor="gender" className="block text-sm font-medium text-gray-700">Gender *</label>
                <select
                  id="gender"
                  name="gender"
                  value={formData.gender || ''}
                  onChange={handleInputChange}
                  required
                  className="mt-1 block w-full px-3 py-2 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                >
                  <option value="Male">Male</option>
                  <option value="Female">Female</option>
                  <option value="Other">Other</option>
                  <option value="Unknown">Unknown</option>
                </select>
              </div>

              <div>
                <label htmlFor="birthDate" className="block text-sm font-medium text-gray-700">Birth Date</label>
                <input
                  type="date"
                  id="birthDate"
                  name="birthDate"
                  value={formData.birthDate || ''}
                  onChange={handleInputChange}
                  className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                />
              </div>

              <div>
                <label htmlFor="deathDate" className="block text-sm font-medium text-gray-700">Death Date</label>
                <input
                  type="date"
                  id="deathDate"
                  name="deathDate"
                  value={formData.deathDate || ''}
                  onChange={handleInputChange}
                  className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                />
              </div>

              <div>
                <label htmlFor="birthPlace" className="block text-sm font-medium text-gray-700">Birth Place</label>
                <input
                  type="text"
                  id="birthPlace"
                  name="birthPlace"
                  value={formData.birthPlace || ''}
                  onChange={handleInputChange}
                  className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                />
              </div>

              <div>
                <label htmlFor="parentId1" className="block text-sm font-medium text-gray-700">Parent 1</label>
                <select
                  id="parentId1"
                  name="parentId1"
                  value={formData.parentId1 || ''}
                  onChange={handleInputChange}
                  className="mt-1 block w-full px-3 py-2 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                >
                  <option value="">Select Parent 1</option>
                  {familyMembers
                    .filter(member => member.id.toString() !== selectedMember?.id?.toString())
                    .map(member => (
                      <option key={member.id} value={member.id.toString()}>{member.fullName}</option>
                    ))}
                </select>
              </div>

              <div>
                <label htmlFor="parentId2" className="block text-sm font-medium text-gray-700">Parent 2</label>
                <select
                  id="parentId2"
                  name="parentId2"
                  value={formData.parentId2 || ''}
                  onChange={handleInputChange}
                  className="mt-1 block w-full px-3 py-2 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                >
                  <option value="">Select Parent 2</option>
                  {familyMembers
                    .filter(member => member.id.toString() !== selectedMember?.id?.toString() && member.id.toString() !== formData.parentId1)
                    .map(member => (
                      <option key={member.id} value={member.id.toString()}>{member.fullName}</option>
                    ))}
                </select>
              </div>

              <div className="flex justify-end space-x-3 pt-4">
                {modalMode === 'edit' && (
                  <button
                    type="button"
                    onClick={() => handleDeleteMember(selectedMember?.id?.toString())}
                    disabled={isLoading}
                    className="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded disabled:opacity-50"
                  >
                    {isLoading ? 'Deleting...' : 'Delete'}
                  </button>
                )}
                <button
                  type="button"
                  onClick={handleCloseModal}
                  className="bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={isLoading}
                  className="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded disabled:opacity-50"
                >
                  {isLoading ? 'Saving...' : (modalMode === 'edit' ? 'Save Changes' : 'Add Member')}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* New Modal for Adding User to Family */}
      {isAddUserModalOpen && (
        <div className="fixed inset-0 bg-gray-600 bg-opacity-75 overflow-y-auto h-full w-full flex justify-center items-center z-50">
          <div className="bg-white p-6 sm:p-8 rounded-lg shadow-xl w-full max-w-md mx-4">
            <div className="flex justify-between items-center mb-4">
              <h2 className="text-xl sm:text-2xl font-semibold text-gray-800">Add User to Family</h2>
              <button onClick={closeAddUserModal} className="text-gray-400 hover:text-gray-600">
                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12"></path></svg>
              </button>
            </div>
            <form onSubmit={handleAddUserSubmit}>
              <div className="mb-4">
                <label htmlFor="addUserEmail" className="block text-sm font-medium text-gray-700 mb-1">
                  User&apos;s Email Address
                </label>
                <input
                  type="email"
                  id="addUserEmail"
                  name="addUserEmail"
                  value={addUserEmail}
                  onChange={(e) => setAddUserEmail(e.target.value)}
                  required
                  className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                  placeholder="user@example.com"
                />
              </div>

              {addUserFeedback && (
                <div
                  className={`mb-4 p-3 rounded-md text-sm ${
                    addUserFeedback.type === 'success' ? 'bg-green-100 text-green-700 border border-green-300' : 'bg-red-100 text-red-700 border border-red-300'
                  }`}
                >
                  {addUserFeedback.message}
                </div>
              )}

              <div className="flex justify-end space-x-3 mt-6">
                <button
                  type="button"
                  onClick={closeAddUserModal}
                  className="px-4 py-2 text-sm font-medium text-gray-700 bg-gray-100 hover:bg-gray-200 rounded-md border border-gray-300 shadow-sm"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={isAddingUser || !selectedFamilyId}
                  className="px-4 py-2 text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 rounded-md shadow-sm disabled:bg-indigo-400 disabled:cursor-not-allowed"
                >
                  {isAddingUser ? 'Adding...' : 'Add User'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* New Modal for Removing User from Family */}
      {isRemoveUserModalOpen && (
        <div className="fixed inset-0 bg-gray-600 bg-opacity-75 overflow-y-auto h-full w-full flex justify-center items-center z-50">
          <div className="bg-white p-6 sm:p-8 rounded-lg shadow-xl w-full max-w-md mx-4">
            <div className="flex justify-between items-center mb-4">
              <h2 className="text-xl sm:text-2xl font-semibold text-gray-800">Remove User from Family</h2>
              <button onClick={closeRemoveUserModal} className="text-gray-400 hover:text-gray-600">
                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12"></path></svg>
              </button>
            </div>
            <form onSubmit={handleRemoveUserSubmit}>
              {isLoadingUsersForRemoval && <p className="text-sm text-gray-600 mb-2">Loading users...</p>}
              {!isLoadingUsersForRemoval && usersInFamilyForRemoval.length === 0 && (
                <p className="text-sm text-gray-600 mb-4">No other users in this family to remove.</p>
              )}
              {!isLoadingUsersForRemoval && usersInFamilyForRemoval.length > 0 && (
                <div className="mb-4">
                  <label htmlFor="removeUserSelect" className="block text-sm font-medium text-gray-700 mb-1">
                    Select User to Remove
                  </label>
                  <select
                    id="removeUserSelect"
                    name="removeUserSelect"
                    value={selectedUserToRemoveId || ''}
                    onChange={(e) => setSelectedUserToRemoveId(e.target.value)}
                    required
                    className="mt-1 block w-full px-3 py-2 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
                  >
                    {usersInFamilyForRemoval.map(user => (
                      <option key={user.id} value={user.id.toString()}>
                        {user.email} (ID: {user.id})
                      </option>
                    ))}
                  </select>
                </div>
              )}

              {removeUserFeedback && (
                <div
                  className={`mb-4 p-3 rounded-md text-sm ${
                    removeUserFeedback.type === 'success' ? 'bg-green-100 text-green-700 border border-green-300' : 'bg-red-100 text-red-700 border border-red-300'
                  }`}
                >
                  {removeUserFeedback.message}
                </div>
              )}

              <div className="flex justify-end space-x-3 mt-6">
                <button
                  type="button"
                  onClick={closeRemoveUserModal}
                  className="px-4 py-2 text-sm font-medium text-gray-700 bg-gray-100 hover:bg-gray-200 rounded-md border border-gray-300 shadow-sm"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={isRemovingUser || isLoadingUsersForRemoval || usersInFamilyForRemoval.length === 0 || !selectedUserToRemoveId}
                  className="px-4 py-2 text-sm font-medium text-white bg-red-600 hover:bg-red-700 rounded-md shadow-sm disabled:bg-red-400 disabled:cursor-not-allowed"
                >
                  {isRemovingUser ? 'Removing...' : 'Remove User'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
